
# Execute on branch and event 

# Environmental Variable 

# Jobs

# Build

# Checkout the gitrepo

# set node js version 

# install node dependencises 

#run the unit testing 

# create artifact folder 

# zip ortifacts 

# upload artifacts

# upload arm template to artifact

# deploy stage 

# downlaod artifact 

# unzip artifact 

# azure login for azure portal 

# provision webapp - run the ARM template 

# deploy artifact to web aspp 

# run funcation testing 

# use node version 

# run funcation testing 



